server:
  port: 45000
spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pet_transaction?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    initialization-mode: always
    continue-on-error: false
    schema: classpath:sql/schema.sql

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.fisco.app.entity
  inject-sql-session-on-mapper-scan: true

logging:
  file:
    name: log/log.log
  level:
    root: info
    com: debug